traefik:
  image:  # @schema additionalProperties: false
    # -- Traefik image host registry
    registry: docker.io
    # -- Traefik image repository
    repository: traefik
    # -- defaults to appVersion
    tag:  # @schema type:[string, null]
    # -- Traefik image pull policy
    pullPolicy: IfNotPresent